SOURCES= hashcons.mli hashcons.ml dnsparameters.ml dnsrr.mli \
	dnstrie.mli dnsrr.ml dnstrie.ml dnsquery.ml dnsloader.ml \
	dnsparser.mli dnslexer.mll dnsparser.mly dnsserver.mli \
	dnsserver.ml bonjour.ml
RESULT=		dns
MPL_AUTOGEN=	dns_rr dns
MELANGE_LIBS=	ounix

include ../../mk/lib.mk
