# $Id$

OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = ounix_stubs.c olog.mli olog.ml ounix.mli ounix.ml
RESULT = ounix
LIBS = unix


native: ncl
bytecode: bcl

all: native bytecode

depend:

include $(OCAMLMAKEFILE)
