depend:
	cd ounix && ${MAKE} depend
	cd ssh && ${MAKE} depend
	cd dns && ${MAKE} depend

all:
	cd ounix && ${MAKE} all
	cd ssh && ${MAKE} all
	cd dns && ${MAKE} all

clean:
	cd ounix && ${MAKE} clean
	cd ssh && ${MAKE} clean
	cd dns && ${MAKE} clean

