RESULT= config
SOURCES= config_location.ml config_t.ml config_parser.mli \
	config_lexer.ml config_parser.ml config.ml
TRASH= config_parser.output config_parser.ml \
	config_lexer.ml config_parser.mli
DISTS=getopt
include ../../mk/lib.mk

