RESULT=		config
SOURCES=	config.ml config_location.ml config_parser.mli \
		config_lexer.ml config_parser.ml
TRASH=		config_parser.output config_parser.ml \
		config_lexer.ml config_parser.mli

include ../../mk/lib.mk

