SOURCES = server.ml ssh_openssh_formats.ml sshd_config.ml sshd.ml
RESULT = sshd

LIBS= 		unix nums cryptokit str
USE_MPL=	Yes
USE_SPL=	Yes
MELANGE_LIBS=	ounix ssh config
DISTS=		cryptokit

include ../../mk/prog.mk
