SOURCES = conf.ml gen_deens_ml.ml
RESULT = gen_deens_ml

LIBS=		unix str getopt config
CONFDIR=	../../lib/config ../../dist/getopt
LIBDIRS=	$(CONFDIR)
INCDIRS=	$(CONFDIR)

OCAMLMAKEFILE=../../OCamlMakefile
include $(OCAMLMAKEFILE)

